---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: giftless
  annotations:
    github.com/project-slug: hhru/giftless
  tags:
    - backend
    - python
spec:
  type: service
  lifecycle: production
